[package]
name = "rusty-gbc"
version = "0.1.0"
authors = ["Cory.Lanza <Cory.Lanza@roadscholar.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
text_io = "0.1.8"
rand = "0.5"
sdl2 = "0.33"