name: Update Personal Site

on:
  push:
    branches: [ master ]

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: docs/.
        dst_path: /Core/wwwroot/
        clean: true
        dst_owner: corylanza
        dst_repo_name: corylanza.github.io
        dst_branch: master
        src_branch: master
        username: corylanza
        email: corylanza@gmail.com
        commit_message: 'Automatic update from rusty-gbc repo'
