name: Update Personal Site

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        override: true
    - run: cargo install -f cargo-web
    - run: cd gbc_wasm
    - run: cargo web deploy --release --all-features --target=wasm32-unknown-unknown      
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: target/deploy/.
        dst_path: /Core/wwwroot/rusty-gbc-dist/
        clean: true
        dst_owner: corylanza
        dst_repo_name: corylanza.github.io
        dst_branch: rust-test
        src_branch: master
        username: corylanza
        email: corylanza@gmail.com
        commit_message: 'Automatic update from rusty-gbc repo'
